# This workflow will install CSS build dependencies and run the CSS build

name: Build CSS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: |
          apt-get install sassc
          npm install autoprefixer cssnano postcss postcss-cli

      - name: Build CSS
        run: |
          ./build-css.sh
